"""쉼터 · 이벤트 · 날씨 데이터 (데모용 고정 데이터셋)."""

from __future__ import annotations

import math

from .geo import haversine
from .models import COOLING, HEATING, Event, Place, Weather

USER_HOME = (37.5662, 126.9784)   # 사용자 현재 위치 (서울시청 앞, 위경도)

BOTH = (COOLING, HEATING)

PLACES: list[Place] = [
    Place(
        id="P01",
        name="중앙시립도서관",
        category="library",
        address="한빛구 중앙로 121",
        lat=37.5663,
        lon=126.9779,
        modes=BOTH,
        summary="층고가 높은 열람실과 대형 공조 설비를 갖춘 공공 도서관. 눈치 없이 오래 머물 수 있습니다.",
        why="1km 반경에서 체감 온도 격차가 가장 크고, 좌석 대비 이용률이 낮아 장시간 회복에 적합합니다.",
        open_from=9,
        open_to=22,
        official=True,
        seats=420,
        capacity=900,
        base_crowd=0.31,
        indoor_cool=23.0,
        indoor_heat=23.5,
        humidity=42,
        airflow="우수",
        aqi=15,
        purchase_required=False,
        staff_pressure=0.05,
        quiet=0.92,
        amenities=["무료 와이파이", "콘센트", "정수기", "열람석", "휠체어 접근"],
    ),
    Place(
        id="P02",
        name="그린백화점 본점",
        category="dept",
        address="한빛구 백화점길 8",
        lat=37.5648,
        lon=126.9817,
        modes=(COOLING,),
        summary="지하 식품관과 8층 휴게 라운지가 개방된 대형 백화점. 냉방이 가장 강한 시간대는 오후입니다.",
        why="강력한 상시 냉방과 넓은 휴게 공간이 있어 짧은 회복에 좋습니다. 다만 혼잡 시간에는 좌석 확보가 어렵습니다.",
        open_from=10,
        open_to=20,
        seats=180,
        capacity=2200,
        base_crowd=0.52,
        indoor_cool=20.5,
        indoor_heat=23.0,
        humidity=48,
        airflow="우수",
        aqi=22,
        purchase_required=False,
        staff_pressure=0.35,
        quiet=0.28,
        amenities=["휴게 라운지", "수유실", "화장실", "푸드코트"],
    ),
    Place(
        id="P03",
        name="시청역 지하상가 쿨스팟",
        category="underground",
        address="한빛구 시청대로 1",
        lat=37.5657,
        lon=126.977,
        modes=BOTH,
        summary="지하상가 중앙 통로에 마련된 개방형 쉼터. 벤치와 냉수기가 있습니다.",
        why="지하 특성상 외기 영향이 적어 온도가 안정적입니다. 통로형 공간이라 소음은 있는 편입니다.",
        inside_mall=True,
        unit="지하 1층 · B-12 구역",
        floor_hint="B1",
        open_from=7,
        open_to=23,
        official=True,
        seats=48,
        capacity=400,
        base_crowd=0.44,
        indoor_cool=24.5,
        indoor_heat=21.0,
        humidity=55,
        airflow="보통",
        aqi=38,
        purchase_required=False,
        staff_pressure=0.12,
        quiet=0.35,
        amenities=["냉수기", "벤치", "화장실", "지하철 연결"],
    ),
    Place(
        id="P04",
        name="한빛역 대합실",
        category="subway",
        address="한빛구 역전대로 1",
        lat=37.5547,
        lon=126.9707,
        modes=BOTH,
        summary="24시간 개방되는 역사 대합실. 냉난방이 항상 가동됩니다.",
        why="언제든 이용 가능하고 무료입니다. 다만 출퇴근 시간에는 매우 혼잡합니다.",
        always_open=True,
        official=True,
        seats=64,
        capacity=800,
        base_crowd=0.40,
        indoor_cool=25.0,
        indoor_heat=21.5,
        humidity=52,
        airflow="보통",
        aqi=42,
        staff_pressure=0.08,
        quiet=0.25,
        amenities=["24시간", "화장실", "냉수기", "교통 연계"],
    ),
    Place(
        id="P05",
        name="행복동 주민센터",
        category="gov",
        address="한빛구 행복로 45",
        lat=37.5636,
        lon=126.9853,
        modes=BOTH,
        summary="공식 지정 무더위·한파 쉼터. 2층 다목적실이 개방됩니다.",
        why="공식 쉼터로 지정되어 있어 이용에 전혀 눈치가 보이지 않습니다. 운영 시간이 짧은 점만 유의하세요.",
        weekend_closed=True,
        open_from=9,
        open_to=18,
        official=True,
        seats=70,
        capacity=160,
        base_crowd=0.22,
        indoor_cool=24.0,
        indoor_heat=24.0,
        humidity=44,
        airflow="양호",
        aqi=20,
        staff_pressure=0.02,
        quiet=0.7,
        amenities=["무료 생수", "안마의자", "혈압계", "정수기"],
    ),
    Place(
        id="P06",
        name="한빛은행 강변지점",
        category="bank",
        address="한빛구 강변로 210",
        lat=37.566,
        lon=126.9827,
        modes=BOTH,
        summary="넓은 대기 공간과 소파를 갖춘 지점. 창구 업무 시간에만 개방됩니다.",
        why="쾌적하지만 대기 고객용 공간이라 장시간 체류는 권장되지 않습니다.",
        weekend_closed=True,
        open_from=9,
        open_to=16,
        seats=26,
        capacity=80,
        base_crowd=0.38,
        indoor_cool=23.5,
        indoor_heat=23.0,
        humidity=41,
        airflow="양호",
        aqi=18,
        staff_pressure=0.62,
        quiet=0.6,
        amenities=["소파", "정수기", "화장실"],
    ),
    Place(
        id="P07",
        name="카페 아르떼",
        category="cafe",
        address="한빛구 문화로 33",
        lat=37.5638,
        lon=126.9827,
        modes=BOTH,
        summary="상가 2층의 조용한 카페. 창가 좌석과 콘센트가 넉넉합니다.",
        why="쾌적도는 높지만 음료 주문이 필요하고, 혼잡 시간에는 체류 시간 제한이 있습니다.",
        inside_mall=True,
        unit="2층 · 205호",
        floor_hint="2F",
        open_from=8,
        open_to=22,
        seats=54,
        capacity=90,
        base_crowd=0.47,
        indoor_cool=23.0,
        indoor_heat=24.0,
        humidity=46,
        airflow="양호",
        aqi=24,
        purchase_required=True,
        staff_pressure=0.55,
        quiet=0.68,
        amenities=["콘센트", "와이파이", "창가석"],
    ),
    Place(
        id="P08",
        name="별빛 시네마",
        category="cinema",
        address="한빛구 노을대로 77",
        lat=37.5615,
        lon=126.9855,
        modes=(COOLING,),
        summary="상영관 외 로비 라운지가 무료 개방됩니다. 냉방이 매우 강합니다.",
        why="가장 낮은 실내 온도를 제공합니다. 다만 로비는 관람객 동선이라 오래 앉아있기 애매합니다.",
        inside_mall=True,
        unit="지하 2층 · 로비 라운지",
        floor_hint="B2",
        open_from=10,
        open_to=25,
        seats=40,
        capacity=300,
        base_crowd=0.36,
        indoor_cool=19.5,
        indoor_heat=22.0,
        humidity=50,
        airflow="우수",
        aqi=28,
        staff_pressure=0.48,
        quiet=0.45,
        amenities=["강냉방", "화장실", "소파"],
    ),
    Place(
        id="P09",
        name="새벽전통시장 온열쉼터",
        category="market",
        address="한빛구 새벽시장길 12",
        lat=37.559,
        lon=126.9776,
        modes=(HEATING,),
        summary="시장 상인회가 운영하는 난방 쉼터. 온수와 온열 매트가 준비되어 있습니다.",
        why="한파 시 상인과 이용객 모두에게 개방되는 공간으로, 난방 체감이 매우 좋습니다.",
        open_from=6,
        open_to=20,
        official=True,
        seats=32,
        capacity=70,
        base_crowd=0.34,
        indoor_cool=27.0,
        indoor_heat=25.5,
        humidity=38,
        airflow="보통",
        aqi=34,
        staff_pressure=0.14,
        quiet=0.3,
        amenities=["온열매트", "온수", "난로", "무료 차"],
    ),
    Place(
        id="P10",
        name="중앙종합병원 로비",
        category="hospital",
        address="한빛구 건강로 5",
        lat=37.5645,
        lon=126.9868,
        modes=BOTH,
        summary="1층 대기 로비가 24시간 개방됩니다. 항온항습이 유지됩니다.",
        why="온도가 가장 안정적이지만 환자 동선이므로 배려가 필요합니다.",
        always_open=True,
        seats=120,
        capacity=400,
        base_crowd=0.42,
        indoor_cool=23.5,
        indoor_heat=23.5,
        humidity=40,
        airflow="우수",
        aqi=12,
        staff_pressure=0.44,
        quiet=0.66,
        amenities=["24시간", "정수기", "화장실", "편의점"],
    ),
    Place(
        id="P11",
        name="노을복합쇼핑몰",
        category="mall",
        address="한빛구 노을대로 120",
        lat=37.5638,
        lon=126.98,
        modes=BOTH,
        summary="아트리움 중앙 광장에 자유석이 넓게 배치된 복합몰입니다.",
        why="좌석이 매우 많아 혼잡해도 자리를 찾기 쉽습니다. 이벤트가 잦아 소음이 있을 수 있습니다.",
        open_from=10,
        open_to=22,
        seats=260,
        capacity=2600,
        base_crowd=0.49,
        indoor_cool=22.0,
        indoor_heat=23.0,
        humidity=47,
        airflow="우수",
        aqi=26,
        staff_pressure=0.22,
        quiet=0.22,
        amenities=["자유석", "화장실", "푸드코트", "수유실", "주차"],
    ),
    Place(
        id="P12",
        name="은빛경로복지관",
        category="center",
        address="한빛구 은빛로 9",
        lat=37.5605,
        lon=126.9925,
        modes=BOTH,
        summary="어르신 우선 이용 시설이지만 한파·폭염 시 전 연령에 개방됩니다.",
        why="난방이 가장 따뜻하게 유지되며 무료 급식과 휴게실이 있습니다.",
        weekend_closed=True,
        open_from=8,
        open_to=18,
        official=True,
        seats=96,
        capacity=200,
        base_crowd=0.29,
        indoor_cool=24.5,
        indoor_heat=25.0,
        humidity=43,
        airflow="양호",
        aqi=19,
        staff_pressure=0.18,
        quiet=0.62,
        amenities=["휴게실", "온수", "무료 급식", "안마의자"],
    ),
    Place(
        id="P13",
        name="스마일문고",
        category="bookstore",
        address="한빛구 책방길 3",
        lat=37.5709,
        lon=126.9784,
        modes=BOTH,
        summary="독서 테이블을 개방한 동네 대형 서점입니다.",
        why="조용하고 쾌적하지만 좌석이 적어 오래 앉아있으면 눈치가 보일 수 있습니다.",
        open_from=10,
        open_to=22,
        seats=34,
        capacity=180,
        base_crowd=0.41,
        indoor_cool=23.8,
        indoor_heat=23.2,
        humidity=44,
        airflow="양호",
        aqi=21,
        staff_pressure=0.5,
        quiet=0.8,
        amenities=["독서 테이블", "와이파이", "화장실"],
    ),
    Place(
        id="P14",
        name="쿨존 편의점 하늘점",
        category="store",
        address="한빛구 하늘로 61",
        lat=37.568,
        lon=126.976,
        modes=(COOLING,),
        summary="테이블석을 갖춘 24시간 편의점. '쿨존' 스티커 가맹점입니다.",
        why="언제나 열려 있지만 좌석이 적고 구매가 사실상 필요합니다. 짧은 휴식용입니다.",
        always_open=True,
        seats=12,
        capacity=40,
        base_crowd=0.33,
        indoor_cool=22.5,
        indoor_heat=24.0,
        humidity=49,
        airflow="보통",
        aqi=30,
        purchase_required=True,
        staff_pressure=0.6,
        quiet=0.3,
        amenities=["24시간", "테이블석", "냉음료"],
    ),
    Place(
        id="P15",
        name="강변공원 그늘쉼터",
        category="park",
        address="한빛구 강변공원 내",
        lat=37.569,
        lon=126.979,
        modes=(COOLING,),
        summary="쿨링포그와 그늘막이 설치된 야외 쉼터입니다.",
        why="실내는 아니지만 쿨링포그로 체감 온도가 5°C 이상 낮습니다. 바람이 잘 통합니다.",
        open_from=6,
        open_to=23,
        official=True,
        seats=80,
        capacity=300,
        base_crowd=0.26,
        indoor_cool=29.0,
        indoor_heat=8.0,
        humidity=58,
        airflow="우수",
        aqi=25,
        staff_pressure=0.0,
        quiet=0.5,
        amenities=["쿨링포그", "그늘막", "음수대", "벤치"],
    ),
    Place(
        id="P16",
        name="도심역 환승통로 쉼터",
        category="subway",
        address="한빛구 도심대로 40",
        lat=37.5662,
        lon=126.9915,
        modes=BOTH,
        summary="환승 통로에 설치된 벤치 구역. 상시 공조가 가동됩니다.",
        why="접근성이 매우 좋지만 유동 인구가 많아 조용한 휴식에는 적합하지 않습니다.",
        inside_mall=True,
        unit="지하 2층 · 환승통로 C",
        floor_hint="B2",
        always_open=True,
        official=True,
        seats=28,
        capacity=500,
        base_crowd=0.5,
        indoor_cool=25.5,
        indoor_heat=21.0,
        humidity=54,
        airflow="보통",
        aqi=44,
        staff_pressure=0.06,
        quiet=0.18,
        amenities=["24시간", "벤치", "교통 연계"],
    ),
    Place(
        id="P17",
        name="하나로은행 중앙점",
        category="bank",
        address="한빛구 중앙로 88",
        lat=37.5675,
        lon=126.982,
        modes=(HEATING,),
        summary="난방이 강하게 유지되는 넓은 영업점입니다.",
        why="겨울철 실내 온도가 높게 유지됩니다. 업무 시간에만 이용 가능합니다.",
        weekend_closed=True,
        open_from=9,
        open_to=16,
        seats=30,
        capacity=90,
        base_crowd=0.36,
        indoor_cool=24.0,
        indoor_heat=24.5,
        humidity=39,
        airflow="양호",
        aqi=17,
        staff_pressure=0.58,
        quiet=0.62,
        amenities=["소파", "온수", "화장실"],
    ),
    Place(
        id="P18",
        name="코지 북카페",
        category="cafe",
        address="한빛구 강변로 340",
        lat=37.572,
        lon=126.986,
        modes=(HEATING,),
        summary="벽난로 인테리어의 아늑한 북카페입니다.",
        why="난방 체감이 매우 좋지만 주문이 필요하고 좌석 회전이 빠릅니다.",
        inside_mall=True,
        unit="1층 · 102호",
        floor_hint="1F",
        open_from=9,
        open_to=23,
        seats=38,
        capacity=70,
        base_crowd=0.45,
        indoor_cool=24.5,
        indoor_heat=25.0,
        humidity=42,
        airflow="보통",
        aqi=23,
        purchase_required=True,
        staff_pressure=0.57,
        quiet=0.72,
        amenities=["콘센트", "와이파이", "도서"],
    ),
    Place(
        id="P19",
        name="한빛시립미술관 로비",
        category="museum",
        address="한빛구 예술로 17",
        lat=37.564,
        lon=126.9738,
        modes=BOTH,
        summary="전시 관람 없이도 개방되는 1층 로비 라운지입니다.",
        why="항온항습으로 관리되어 온도 편차가 거의 없고, 조용합니다.",
        open_from=10,
        open_to=19,
        seats=88,
        capacity=260,
        base_crowd=0.27,
        indoor_cool=23.0,
        indoor_heat=23.0,
        humidity=45,
        airflow="우수",
        aqi=14,
        staff_pressure=0.2,
        quiet=0.85,
        amenities=["라운지", "카페", "화장실", "와이파이"],
    ),
    Place(
        id="P20",
        name="청소년문화의집",
        category="center",
        address="한빛구 배움로 24",
        lat=37.575,
        lon=126.977,
        modes=BOTH,
        summary="스터디룸과 휴게 라운지를 무료 개방하는 공공시설입니다.",
        why="공공시설이라 눈치가 없고 좌석도 넉넉합니다. 방과 후 시간대에는 붐빕니다.",
        open_from=9,
        open_to=21,
        official=True,
        seats=110,
        capacity=240,
        base_crowd=0.3,
        indoor_cool=23.5,
        indoor_heat=23.8,
        humidity=43,
        airflow="양호",
        aqi=18,
        staff_pressure=0.05,
        quiet=0.6,
        amenities=["스터디룸", "와이파이", "콘센트", "정수기"],
    ),
]

PLACES_BY_ID = {p.id: p for p in PLACES}


EVENTS: list[Event] = [
    Event(
        id="E1",
        title="한여름 밤 워터 페스티벌",
        lat=37.5657,
        lon=126.977,
        radius=500.0,
        start_hour=17,
        end_hour=22,
        boost=0.42,
        modes=(COOLING,),
        note="시청 앞 광장 일대 · 예상 방문 1.2만 명",
    ),
    Event(
        id="E2",
        title="청년 채용 박람회",
        lat=37.5638,
        lon=126.98,
        radius=350.0,
        start_hour=10,
        end_hour=17,
        boost=0.33,
        modes=(COOLING, HEATING),
        note="노을복합쇼핑몰 컨벤션홀 · 3일차",
    ),
    Event(
        id="E3",
        title="겨울 빛 축제",
        lat=37.57,
        lon=126.979,
        radius=450.0,
        start_hour=16,
        end_hour=22,
        boost=0.4,
        modes=(HEATING,),
        note="중앙로 일대 점등 행사",
    ),
    Event(
        id="E4",
        title="주말 플리마켓",
        lat=37.559,
        lon=126.9776,
        radius=320.0,
        start_hour=11,
        end_hour=18,
        boost=0.3,
        modes=(COOLING, HEATING),
        note="새벽전통시장 특설 매대 · 주말 한정",
        weekend_only=True,
    ),
]


# ---------------------------------------------------------------------------
# 날씨
# ---------------------------------------------------------------------------
def weather_for(mode: str, hour: int, minute: int = 0) -> Weather:
    """모드와 시각에 따른 외기 상태 (데모용 결정론적 곡선)."""
    t = hour + minute / 60.0
    if mode == COOLING:
        # 새벽 28도 ~ 오후 3시 최고 36.5도
        temp = 32.2 + 4.3 * math.sin((t - 9.0) / 24.0 * 2 * math.pi)
        humid = int(62 - 14 * math.sin((t - 9.0) / 24.0 * 2 * math.pi))
        feels = temp + (humid - 45) * 0.09
        alert = "폭염경보" if temp >= 35 else ("폭염주의보" if temp >= 33 else "")
        condition = "매우 더움" if temp >= 34 else "더움"
    else:
        # 새벽 -11도 ~ 오후 2시 -2도
        temp = -6.6 + 4.6 * math.sin((t - 8.5) / 24.0 * 2 * math.pi)
        humid = int(48 + 10 * math.sin((t - 3.0) / 24.0 * 2 * math.pi))
        feels = temp - 4.2  # 체감 (바람)
        alert = "한파경보" if temp <= -9 else ("한파주의보" if temp <= -5 else "")
        condition = "매우 추움" if temp <= -8 else "추움"
    return Weather(
        outdoor=round(temp, 1),
        feels=round(feels, 1),
        humidity=max(15, min(95, humid)),
        condition=condition,
        alert=alert,
    )


def distance(a: tuple[float, float], b: tuple[float, float]) -> float:
    """두 (위도, 경도) 사이 거리 (미터)."""
    return haversine(a, b)


def walk_minutes(meters: float) -> int:
    """도보 시간 (분). 평균 67m/분."""
    return max(1, round(meters / 67.0))


def distance_label(meters: float) -> str:
    if meters >= 1000:
        return f"{meters / 1000:.1f}km"
    return f"{int(round(meters / 10) * 10)}m"
